//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.10 at 07:02:54 PM CEST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://test/summary", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.pseudoorganization.pseudosystemsintegration.controllers.soap;
