services:
  mysql:
    image: "mysql:latest"
    environment:
      - "MYSQL_DATABASE=mydatabase"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=verysecret"
      - "MYSQL_USER=myuser"
    ports:
      - "3306:3306"
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "-u$MYSQL_USER",
          "-p$MYSQL_PASSWORD",
          "ping",
          "-h",
          "localhost",
        ]
      timeout: 20s
      retries: 10
    networks:
      - internal

  backend:
    build:
      context: ./backend
      args:
        DOCKER_BUILDKIT: 1
    environment:
      - "MYSQL_URL=jdbc:mysql://mysql/mydatabase"
      - "MYSQL_USER=myuser"
      - "MYSQL_PASSWORD=secret"
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    ports:
      - "8080:8080"
      - "5005:5005"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - internal
      - api

  frontend:
    build:
      context: ./frontend
      args:
        DOCKER_BUILDKIT: 1
    ports:
      - "3000:3000"
    depends_on:
      mysql:
        condition: service_healthy
      backend:
        condition: service_started
    networks:
      - api

networks:
  internal:
  api:
