server:
  port: 8888

spring:
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
  web:
    resources:
      static-locations: file:"/resources/**"
  mvc:
    static-path-pattern: /resources/**
  datasource:
    username: user
    url: jdbc:mysql://localhost:3306/integracje
    password: user
  jpa:
    generate-ddl: 'true'
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  application:
    name: Projekt na inetgracje