//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.10 at 07:02:54 PM CEST 
//


package com.pseudoorganization.pseudosystemsintegration.controllers.soap;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for summary complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="summary"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="population_max_percent" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="crimes_total" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="crimes_total_property" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="crimes_total_violent" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "summary", propOrder = {
        "populationMaxPercent",
        "crimesTotal",
        "crimesTotalProperty",
        "crimesTotalViolent"
})
public class Summary {

    @XmlElement(name = "population_max_percent", required = true)
    protected String populationMaxPercent;
    @XmlElement(name = "crimes_total", required = true)
    protected String crimesTotal;
    @XmlElement(name = "crimes_total_property", required = true)
    protected String crimesTotalProperty;
    @XmlElement(name = "crimes_total_violent", required = true)
    protected String crimesTotalViolent;

    /**
     * Gets the value of the populationMaxPercent property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getPopulationMaxPercent() {
        return populationMaxPercent;
    }

    /**
     * Sets the value of the populationMaxPercent property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setPopulationMaxPercent(String value) {
        this.populationMaxPercent = value;
    }

    /**
     * Gets the value of the crimesTotal property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getCrimesTotal() {
        return crimesTotal;
    }

    /**
     * Sets the value of the crimesTotal property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCrimesTotal(String value) {
        this.crimesTotal = value;
    }

    /**
     * Gets the value of the crimesTotalProperty property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getCrimesTotalProperty() {
        return crimesTotalProperty;
    }

    /**
     * Sets the value of the crimesTotalProperty property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCrimesTotalProperty(String value) {
        this.crimesTotalProperty = value;
    }

    /**
     * Gets the value of the crimesTotalViolent property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getCrimesTotalViolent() {
        return crimesTotalViolent;
    }

    /**
     * Sets the value of the crimesTotalViolent property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCrimesTotalViolent(String value) {
        this.crimesTotalViolent = value;
    }

}
